name = "irb-wizard"
main = "worker.js"
compatibility_date = "2026-02-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = "dist"
not_found_handling = "single-page-application"
